version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airplant
  - aliceblue
  - antiquewhite
  - astro
  - bithound
  - blanchedalmond
  - blueviolet
  - buildable
  - burlywood
  - cadetblue
  - caseta
  - cbar
  - codeowners
  - codez
  - cornflowerblue
  - cornsilk
  - ingverb
  - creationrc
  - csize
  - darkcyan
  - tplink
  - darkgoldenrod
  - darkgray
  - darkgreen
  - darkgrey
  - obsidian
  - immich
  - darkkhaki
  - darkmagenta
  - darkolivegreen
  - darkorange
  - darkorchid
  - darkred
  - darksalmon
  - darkseagreen
  - darkslateblue
  - darkslategray
  - darkslategrey
  - darkturquoise
  - olrapi
  - darkviolet
  - datasources
  - gitea
  - datetime
  - dayslide
  - dbaeumer
  - dedup
  - deeppink
  - deepskyblue
  - devkit
  - dhall
  - dimgray
  - dimgrey
  - dodgerblue
  - dpms
  - duedate
  - ecobee
  - entites
  - esbenp
  - execa
  - exiasr
  - falsey
  - fastify
  - floralwhite
  - forestgreen
  - gainsboro
  - gbit
  - ghostwhite
  - googlemaps
  - gotify
  - greenyellow
  - gridsome
  - grocy
  - hadolint
  - hass
  - hassio
  - healthcheck
  - homeassistant
  - hotpink
  - hsts
  - hvac
  - idris
  - indianred
  - intellij
  - interwebs
  - julianday
  - kbit
  - keyfile
  - keylist
  - kool
  - kusto
  - lavenderblush
  - lawngreen
  - leadtree
  - lemonchiffon
  - letsencrypt
  - lifecycles
  - lightcoral
  - lightcyan
  - lightgoldenrodyellow
  - lightgray
  - lightgreen
  - lightpink
  - lightsalmon
  - lightseagreen
  - lightskyblue
  - lightslategray
  - lightslategrey
  - lightsteelblue
  - lightyellow
  - limegreen
  - lutron
  - managerrc
  - maxage
  - mbar
  - mbit
  - mediumaquamarine
  - mediumblue
  - mediumorchid
  - mediumpurple
  - mediumseagreen
  - mediumslateblue
  - mediumspringgreen
  - mediumturquoise
  - mediumvioletred
  - microgrowery
  - midnightblue
  - mintcream
  - mireds
  - mistyrose
  - mrad
  - navajowhite
  - navyblue
  - nocheck
  - npmjs
  - nrwl
  - nsoult
  - nxignore
  - oldlace
  - olivedrab
  - openai
  - orangered
  - palegoldenrod
  - palegreen
  - paleturquoise
  - palevioletred
  - pando
  - papayawhip
  - peachpuff
  - pico
  - pino
  - pkief
  - pomodoro
  - postdata
  - powderblue
  - prettyrc
  - printlabel
  - proto
  - proxymanager
  - purescript
  - reftimes
  - rgbw
  - rgbww
  - rosybrown
  - royalblue
  - rrule
  - saddlebrown
  - sandybrown
  - seagreen
  - shellcheck
  - sinm
  - sinonjs
  - skyblue
  - slateblue
  - slategray
  - slategrey
  - snapse
  - sonarjs
  - springgreen
  - steelblue
  - terminalizer
  - testrc
  - timelapse
  - timonwong
  - tmid
  - templow
  - toolbelt
  - tsdoc
  - typeof
  - undici
  - unitless
  - vividra
  - barcodes
  - unpublish
  - userfields
  - visbility
  - userentities
  - vsix
  - whitesmoke
  - womp
  - writerrc
  - wttr
  - yellowgreen
  - zipignore
ignoreWords: []
import: []
